export const products = [
  {
    id: "celestial-diamond-cascade",
    name: "Celestial Diamond Cascade",
    collection: "The Heritage Line",
    price: 185000,
    originalPrice: 210000,
    description: "An ethereal waterfall of brilliant-cut diamonds set in lustrous white gold. This statement necklace set features cascading teardrop motifs with matching chandelier earrings — a masterpiece for the woman who commands attention.",
    details: [
      "Metal: 18K White Gold Rhodium Plated",
      "Stones: AAA Grade Cubic Zirconia",
      "Necklace Length: 16–18 inches (adjustable)",
      "Earring Drop: 2.5 inches",
      "Clasp: Lobster claw with safety chain",
      "Set Includes: Necklace + Earrings pair"
    ],
    images: ["/products/product-1.jpg"],
    category: "necklace-sets",
    tags: ["diamond", "bridal", "premium", "bestseller"],
    inStock: true,
    badge: "Bestseller",
  },
  {
    id: "royal-teardrop-symphony",
    name: "Royal Teardrop Symphony",
    collection: "The Imperial Archive",
    price: 165000,
    originalPrice: null,
    description: "A regal symphony of oval and teardrop motifs arranged in a stunning grand collar design. This necklace set exudes old-world opulence reimagined for the modern connoisseur, paired with elegant matching earrings.",
    details: [
      "Metal: 18K White Gold Rhodium Plated",
      "Stones: AAA Grade CZ with Swiss Cut",
      "Necklace Length: 15–17 inches (adjustable)",
      "Earring Drop: 3 inches",
      "Clasp: Box clasp with safety",
      "Set Includes: Necklace + Earrings pair"
    ],
    images: ["/products/product-2.jpg"],
    category: "necklace-sets",
    tags: ["diamond", "bridal", "premium"],
    inStock: true,
    badge: null,
  },
  {
    id: "botanical-leaf-pendant",
    name: "Botanical Leaf Pendant Set",
    collection: "The Garden Collection",
    price: 89000,
    originalPrice: 105000,
    description: "Delicate marquise-cut stones form an enchanting leaf-vine pattern in this refined pendant necklace. The organic motifs are elevated by precision settings and paired with matching leaf-drop earrings.",
    details: [
      "Metal: Silver with White Gold Plating",
      "Stones: Premium CZ, Marquise & Pear Cut",
      "Necklace Length: 16 inches + 2 inch extender",
      "Pendant Drop: 1.5 inches",
      "Clasp: Spring ring",
      "Set Includes: Necklace + Earrings pair"
    ],
    images: ["/products/product-3.jpg"],
    category: "necklace-sets",
    tags: ["diamond", "everyday", "classic"],
    inStock: true,
    badge: "Sale",
  },
  {
    id: "ruby-floral-grandeur",
    name: "Ruby Floral Grandeur",
    collection: "The Imperial Archive",
    price: 225000,
    originalPrice: null,
    description: "Deep crimson rubies framed by crystal-clear floral motifs create an extraordinary piece of wearable art. This set bridges heritage craftsmanship with contemporary design, featuring emerald-cut rubies and flower-link details.",
    details: [
      "Metal: 18K White Gold Rhodium Plated",
      "Stones: Lab-Created Ruby, AAA CZ",
      "Necklace Length: 16–18 inches (adjustable)",
      "Earring Drop: 2.8 inches",
      "Clasp: Hidden box clasp",
      "Set Includes: Necklace + Earrings pair"
    ],
    images: ["/products/product-4.jpg"],
    category: "necklace-sets",
    tags: ["ruby", "bridal", "premium", "statement"],
    inStock: true,
    badge: "New Arrival",
  },
  {
    id: "golden-teardrop-heritage",
    name: "Golden Teardrop Heritage",
    collection: "The Heritage Line",
    price: 135000,
    originalPrice: 155000,
    description: "Inspired by ancestral Indian jewelry traditions, this gold-toned masterpiece features intricate teardrops and floral clusters. A versatile set that transitions beautifully from sacred ceremonies to grand celebrations.",
    details: [
      "Metal: Gold Plated Sterling Silver",
      "Stones: Premium Swiss CZ",
      "Necklace Length: 15–17 inches (adjustable)",
      "Earring Drop: 2 inches",
      "Clasp: Lobster claw",
      "Set Includes: Necklace + Earrings pair"
    ],
    images: ["/products/product-5.jpg"],
    category: "necklace-sets",
    tags: ["gold", "bridal", "traditional"],
    inStock: true,
    badge: null,
  },
  {
    id: "crystal-floral-elegance",
    name: "Crystal Floral Elegance",
    collection: "The Bespoke Vault",
    price: 195000,
    originalPrice: null,
    description: "Emerald-cut crystals alternating with diamond flower motifs create a stunning geometric rhythm. This clear crystal statement set is the epitome of modern luxury — bold yet refined.",
    details: [
      "Metal: 18K White Gold Rhodium Plated",
      "Stones: Swarovski-Grade CZ, Emerald Cut",
      "Necklace Length: 16–18 inches (adjustable)",
      "Earring Drop: 2.5 inches",
      "Clasp: Double-safety box clasp",
      "Set Includes: Necklace + Earrings pair"
    ],
    images: ["/products/product-6.jpg"],
    category: "necklace-sets",
    tags: ["diamond", "premium", "statement"],
    inStock: true,
    badge: null,
  },
  {
    id: "emerald-floral-sovereign",
    name: "Emerald Floral Sovereign",
    collection: "The Imperial Archive",
    price: 245000,
    originalPrice: 280000,
    description: "Rich emerald stones nestled among diamond flower clusters in a design that echoes royal court jewelry. This set combines vivid color with white brilliance for an unforgettable presence.",
    details: [
      "Metal: 18K White Gold Rhodium Plated",
      "Stones: Lab-Created Emerald, AAA CZ",
      "Necklace Length: 16–18 inches (adjustable)",
      "Earring Drop: 2.8 inches",
      "Clasp: Hidden box clasp",
      "Set Includes: Necklace + Earrings pair"
    ],
    images: ["/products/product-7.jpg"],
    category: "necklace-sets",
    tags: ["emerald", "bridal", "premium", "statement"],
    inStock: true,
    badge: "Exclusive",
  },
  {
    id: "rainbow-mosaic-collar",
    name: "Rainbow Mosaic Collar",
    collection: "The Bespoke Vault",
    price: 275000,
    originalPrice: null,
    description: "A kaleidoscope of sapphires, emeralds, and rubies woven into a magnificent collar necklace. This show-stopping multi-stone set is for the bold collector who celebrates all colors of beauty.",
    details: [
      "Metal: 18K White Gold Rhodium Plated",
      "Stones: Multi-color Lab-Created Gems, AAA CZ",
      "Necklace Length: 15–17 inches (adjustable)",
      "Earring Drop: 3 inches",
      "Clasp: Box clasp with safety chain",
      "Set Includes: Necklace + Earrings pair"
    ],
    images: ["/products/product-8.jpg"],
    category: "necklace-sets",
    tags: ["multi-stone", "premium", "statement", "collector"],
    inStock: true,
    badge: "Limited Edition",
  },
  {
    id: "aquamarine-floral-dream",
    name: "Aquamarine Floral Dream",
    collection: "The Garden Collection",
    price: 215000,
    originalPrice: 240000,
    description: "Serene aquamarine stones set among delicate diamond petals create a cool, oceanic beauty. This set captures the tranquility of coastal dawns in a wearable work of art.",
    details: [
      "Metal: 18K White Gold Rhodium Plated",
      "Stones: Lab-Created Aquamarine, AAA CZ",
      "Necklace Length: 16–18 inches (adjustable)",
      "Earring Drop: 2.5 inches",
      "Clasp: Hidden box clasp",
      "Set Includes: Necklace + Earrings pair"
    ],
    images: ["/products/product-9.jpg"],
    category: "necklace-sets",
    tags: ["aquamarine", "premium", "elegant"],
    inStock: true,
    badge: null,
  },
  {
    id: "emerald-vine-enchantment",
    name: "Emerald Vine Enchantment",
    collection: "The Garden Collection",
    price: 145000,
    originalPrice: null,
    description: "Emerald teardrops suspended from diamond-encrusted vine motifs create a botanical fantasy. This set is a tribute to nature's own jewelry — where every leaf tells a story of eternal growth.",
    details: [
      "Metal: Silver with Rhodium Plating",
      "Stones: Lab-Created Emerald, CZ",
      "Necklace Length: 16 inches + 2 inch extender",
      "Earring Drop: 2.2 inches",
      "Clasp: Lobster claw",
      "Set Includes: Necklace + Earrings pair"
    ],
    images: ["/products/product-10.jpg"],
    category: "necklace-sets",
    tags: ["emerald", "classic", "garden"],
    inStock: true,
    badge: null,
  },
  {
    id: "turquoise-oval-majesty",
    name: "Turquoise Oval Majesty",
    collection: "The Heritage Line",
    price: 155000,
    originalPrice: 175000,
    description: "Striking turquoise ovals embraced by intricate oval-link chain work in a design that marries Baroque grandeur with Art Deco precision. A statement set for the discerning collector.",
    details: [
      "Metal: Silver with Heavy Rhodium Plating",
      "Stones: Lab-Created Turquoise, AAA CZ",
      "Necklace Length: 16–18 inches (adjustable)",
      "Earring Drop: 2.5 inches",
      "Clasp: Box clasp with safety",
      "Set Includes: Necklace + Earrings pair"
    ],
    images: ["/products/product-11.jpg"],
    category: "necklace-sets",
    tags: ["turquoise", "statement", "heritage"],
    inStock: true,
    badge: null,
  },
  {
    id: "rose-quartz-oval-grace",
    name: "Rose Quartz Oval Grace",
    collection: "The Bespoke Vault",
    price: 142000,
    originalPrice: null,
    description: "Soft blush rose quartz stones set in an elaborate oval-chain design create an utterly romantic piece. This set whispers femininity and grace in every delicate detail.",
    details: [
      "Metal: Silver with Rhodium Plating",
      "Stones: Natural Rose Quartz, AAA CZ",
      "Necklace Length: 16–18 inches (adjustable)",
      "Earring Drop: 2.3 inches",
      "Clasp: Box clasp",
      "Set Includes: Necklace + Earrings pair"
    ],
    images: ["/products/product-12.jpg"],
    category: "necklace-sets",
    tags: ["rose-quartz", "romantic", "elegant"],
    inStock: true,
    badge: null,
  },
  {
    id: "emerald-oval-sovereign",
    name: "Emerald Oval Sovereign",
    collection: "The Imperial Archive",
    price: 168000,
    originalPrice: 195000,
    description: "Deep forest green emeralds set in an elaborate oval-link framework create a regal masterpiece. This set blends bold color with sophisticated chain architecture for maximum impact.",
    details: [
      "Metal: Silver with Heavy Rhodium Plating",
      "Stones: Lab-Created Emerald, AAA CZ",
      "Necklace Length: 16–18 inches (adjustable)",
      "Earring Drop: 2.5 inches",
      "Clasp: Double-safety box clasp",
      "Set Includes: Necklace + Earrings pair"
    ],
    images: ["/products/product-13.jpg"],
    category: "necklace-sets",
    tags: ["emerald", "premium", "statement"],
    inStock: true,
    badge: "Sale",
  },
  {
    id: "ruby-oval-majesty",
    name: "Ruby Oval Majesty",
    collection: "The Heritage Line",
    price: 172000,
    originalPrice: null,
    description: "Vivid ruby teardrops set in ornate oval-link metalwork create a piece that channels royal opulence. The deep crimson stones against brilliant silver plating make for a truly commanding presence.",
    details: [
      "Metal: Silver with Heavy Rhodium Plating",
      "Stones: Lab-Created Ruby, AAA CZ",
      "Necklace Length: 16–18 inches (adjustable)",
      "Earring Drop: 2.5 inches",
      "Clasp: Box clasp with safety chain",
      "Set Includes: Necklace + Earrings pair"
    ],
    images: ["/products/product-14.jpg"],
    category: "necklace-sets",
    tags: ["ruby", "premium", "heritage"],
    inStock: true,
    badge: null,
  },
  {
    id: "sapphire-oval-empress",
    name: "Sapphire Oval Empress",
    collection: "The Imperial Archive",
    price: 162000,
    originalPrice: 185000,
    description: "Deep sapphire blue stones framed in an elaborate oval-link design evoke the grandeur of empress jewelry. A magnificent set that pairs striking color with architectural metalwork.",
    details: [
      "Metal: Silver with Heavy Rhodium Plating",
      "Stones: Lab-Created Sapphire, AAA CZ",
      "Necklace Length: 16–18 inches (adjustable)",
      "Earring Drop: 2.5 inches",
      "Clasp: Box clasp with safety",
      "Set Includes: Necklace + Earrings pair"
    ],
    images: ["/products/product-15.jpg"],
    category: "necklace-sets",
    tags: ["sapphire", "premium", "statement"],
    inStock: true,
    badge: null,
  },
  {
    id: "sapphire-vine-cascade",
    name: "Sapphire Vine Cascade",
    collection: "The Garden Collection",
    price: 148000,
    originalPrice: null,
    description: "Royal sapphire teardrops dangle from diamond-vine motifs in this cascading beauty. Inspired by the celestial gardens of Mughal architecture, this set is a bridge between history and modernity.",
    details: [
      "Metal: Silver with Rhodium Plating",
      "Stones: Lab-Created Sapphire, AAA CZ",
      "Necklace Length: 16 inches + 2 inch extender",
      "Earring Drop: 2.2 inches",
      "Clasp: Lobster claw",
      "Set Includes: Necklace + Earrings pair"
    ],
    images: ["/products/product-16.jpg"],
    category: "necklace-sets",
    tags: ["sapphire", "garden", "classic"],
    inStock: true,
    badge: null,
  },
  {
    id: "ruby-vine-enchantment",
    name: "Ruby Vine Enchantment",
    collection: "The Garden Collection",
    price: 139000,
    originalPrice: 158000,
    description: "Lustrous ruby teardrops framed by sparkling vine-leaf motifs create a piece of romantic botanical beauty. This set celebrates the fiery passion of rubies tempered by nature-inspired elegance.",
    details: [
      "Metal: Silver with Rhodium Plating",
      "Stones: Lab-Created Ruby, AAA CZ",
      "Necklace Length: 16 inches + 2 inch extender",
      "Earring Drop: 2.2 inches",
      "Clasp: Lobster claw",
      "Set Includes: Necklace + Earrings pair"
    ],
    images: ["/products/product-17.jpg"],
    category: "necklace-sets",
    tags: ["ruby", "garden", "romantic"],
    inStock: true,
    badge: "Sale",
  },
];

export const collections = [
  {
    id: "the-heritage-line",
    name: "The Heritage Line",
    description: "Pieces inspired by ancestral traditions, reimagined for the modern woman.",
    image: "/products/product-1.jpg",
  },
  {
    id: "the-imperial-archive",
    name: "The Imperial Archive",
    description: "Royal grandeur meets contemporary craftsmanship in our most opulent collection.",
    image: "/products/product-4.jpg",
  },
  {
    id: "the-bespoke-vault",
    name: "The Bespoke Vault",
    description: "Statement pieces for the bold collector who celebrates individuality.",
    image: "/products/product-8.jpg",
  },
  {
    id: "the-garden-collection",
    name: "The Garden Collection",
    description: "Nature-inspired motifs capturing the beauty of botanical elegance.",
    image: "/products/product-10.jpg",
  },
];

export function formatPrice(price) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(price);
}

export function getProductById(id) {
  return products.find((p) => p.id === id);
}

export function getProductsByCollection(collectionName) {
  return products.filter((p) => p.collection === collectionName);
}

export function getProductsByTag(tag) {
  return products.filter((p) => p.tags.includes(tag));
}
